#server.port = 9091
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.datasource.url=jdbc:mysql://localhost:3306/school
#spring.datasource.username=root
#spring.datasource.password=password

server
  port:9091
spring
  jpa
    hibernate
      ddl-auto:update
    properties
      hibernate
        dialect:org.hibernate.dialect.MySQL8Dialect
  datasource
    url:jdbc:mysql://localhost:3306/school
    uername:root
    password:password
  cache
    type:redis
  redis
    host:localhost
    port:6379